src/blogging/urls.py
from django.conf.urls import url,include
from django.contrib import admin
# These two are newly imported
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include("posts.urls", namespace="posts")),
]
# This if loop is added now
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/posts/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import(
    post_list,
    post_create,
    post_detail,
    post_update,
    post_delete,
)
urlpatterns = [
    url(r'^$', post_list,name='list'),
    url(r'^create/$', post_create),
    url(r'^(?P<slug>[\w-]+)/$', post_detail,name='detail'),
    url(r'^(?P<slug>[\w-]+)/edit/$', post_update, name="update"),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete),
]

src/comments/models.py
from django.db import models
from django.conf import settings
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from posts.models import Post
# Create your models here.
class Comment(models.Model):
    user      = models.ForeignKey(settings.AUTH_USER_MODEL, default = 1)
    # post      = models.ForeignKey(Post)
    
    # These three item will replace the above commented item
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')

    content   = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return str(self.user.username)

src/posts/models.py
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from markdown_deux import markdown
from django.utils.safestring import mark_safe
def upload_location(instance, filename):
    # Its returning a relative string where it's going.
    return "%s/%s" %(instance.id,filename)

class PostManager(models.Manager):
    # We are over riding the default all
    def active(self, *args, **kwargs):
        # super(PostManager, self) this get the orginal all()
         # it's inheriting from model.Manager
         # super(PostManager, self) is getting orginal all
         # Then we are appending stuff to it
        return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default = 1)
    title = models.CharField(max_length = 120)
    slug = models.SlugField(unique=True)
    image = models.ImageField(upload_to=upload_location,null=True, blank=True,
    width_field="width_field",
    height_field="height_field")
    height_field=models.IntegerField(default=0)
    width_field=models.IntegerField(default=0)
    content = models.TextField()
    draft = models.BooleanField(default = False)
    publish = models.DateField(auto_now = False, auto_now_add=False)
    updated = models.DateTimeField(auto_now= True, auto_now_add = False)
    timestap = models.DateTimeField(auto_now= False, auto_now_add = True)

    objects = PostManager()

    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("posts:detail",kwargs={"slug": self.slug})
    #This makes sure that all the datas are in this order.
    class Meta:
        ordering = ["-timestap", "-updated"]
    def get_markdown(self):
        content = self.content
        # Here its converting the content into markdown
        markdown_text = markdown(content)
        return mark_safe(markdown_text)
def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Post.objects.filter(slug=slug).order_by("-id")
    exists = qs.exists()
    if exists:
        #If exist then it is going to be recursive here
        new_slug = "%s-%s"%(slug, qs.first().id)
        return create_slug(instance, new_slug= new_slug)
    return slug

def pre_save_post_reciver(sender, instance, *args, **kwargs):
    #we know that this function assigns value to slug field
    #if value is not present in it then we do this
    if not instance.slug:
        instance.slug = create_slug(instance)
pre_save.connect(pre_save_post_reciver, sender=Post)

src/posts/forms.py
from django import forms
from .models import Post
from pagedown.widgets import PagedownWidget
class PostForm(forms.ModelForm):
    # The PagedownWidget ischanged to PagedownWidget(show_preview = False)
    # Then we no longer view the image at edit view.  
    content = forms.CharField(widget=PagedownWidget(show_preview = False))
    publish = forms.DateField(widget = forms.SelectDateWidget)
    class Meta:
        model = Post
        fields = [
            "title",
            "image",
            "content",
            "draft",
            "publish",
        ]

src/posts/views.py
from urllib.parse import quote
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect,Http404
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.db.models import Q
# Create your views here.
from .models import Post
from .forms import PostForm

def post_create(request):
    # This line is updated
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    # Add this below code if the above verification is not there
    # if not request.user.is_authenticated():
    #     raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        instance = form.save(commit=False)
        # This assumed that the user is logged in bez Http404 checks it
        # This is newly added line
        instance.user = request.user
        instance.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(instance.get_absolute_url())
    context = {
        "form":form,
    }
    return render(request, "post_form.html", context)

def post_detail(request,slug):
    instance = get_object_or_404(Post, slug=slug)
    if instance.draft or instance.publish > timezone.now().date():
        if not request.user.is_staff or not request.user.is_superuser:
            raise Http404
    # The content share string is passed here
    share_string= quote(instance.content)
    # and it is passed into the context
    context ={
    "title": instance.title,
    "instance":instance,
    "share_string":share_string,
    }
    return render(request, "post_detail.html", context)

def post_list(request):
    today = timezone.now().date()
    queryset_list = Post.objects.active()
    # the below two line segments are added now
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Post.objects.all()
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
        Q(title__icontains = query) |
        Q(content__icontains = query) |
        Q(user__first_name__icontains = query) |
        Q(user__last_name__icontains = query)
        ).distinct()

    paginator = Paginator(queryset_list, 6) # Show 25 contacts per page
    page_request_var = "abc"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        queryset = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        queryset = paginator.page(paginator.num_pages)
    context ={
    "object_list":queryset,
    "title": "List",
    "page_request_var":page_request_var,
    "today":today,
    }
    return render(request, "post_list.html", context)

def post_update(request, slug =None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    # Here it request.FILES or None is added
    form = PostForm(request.POST or None,request.FILES or None ,instance=instance)
    if form.is_valid():
        instance = form.save(commit=False)
        instance.save()
        #extra_tag="some-tag" added to have addon class.
        messages.success(request, "<a href='#'>Item </a> Saved", extra_tags="html_safe")
        return HttpResponseRedirect(instance.get_absolute_url())
    context ={
    "title": instance.title,
    "instance":instance,
    "form":form,
    }
    return render(request, "post_form.html", context)

def post_delete(request, slug =None):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance = get_object_or_404(Post, slug=slug)
    # This line will delete that line form database.
    instance.delete()
    messages.success(request, "Successfully Deleted")
    return redirect("posts:list")

src/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block head_title %}Try Django 1.9{% endblock head_title %}</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    <link rel='stylesheet' href='{% static "css/base.css" %}'>
    <style>
    {% block style %}{% endblock style %}
    </style>
    {% block head_extra %}{% endblock head_extra %}
  </head>
  <body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    {% include "messages_display.html" %}
    <div class="container">
      {% block content %}{% endblock content %}
    </div>

    <!-- Latest compiled and minified JavaScript -->
    <script
			  src="https://code.jquery.com/jquery-1.12.4.min.js"
			  integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
			  crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.6.0/marked.min.js"></script>
    <script type="text/javascript">
      $(document).ready(function(){
        $(".content-markdown").each(function(){
          var content = $(this).text()
          var markedContent = marked(content)
          $(this).html(markedContent);
        })
        $(".post-detail-item img").each(function(){
          $(this).addClass("img-responsive");
        })

        var contentInput = $("#id_content");
        function setContent(value){
          var markedContent = marked(value)
          $("#preview-content").html(markedContent)
          $("#preview-content img").each(function(){
            $(this).addClass("img-responsive")
          })
        }
        setContent(contentInput.val())

        // If any changes are made in keyup then this function will get invoked.
        contentInput.keyup(function(){
          var newContent = $(this).val()
          setContent(newContent)
        })

        var titleInput = $("#id_title");
        // $("#preview-title").text(titleItem.val());
        // Instead of this we are doing
        function setTitle(value){
          $("#preview-title").text(value);
        }
        setTitle(titleInput.val())
        titleInput.keyup(function(){
          var newTitle = $(this).val()
          setTitle(newTitle)
        })
      })
    </script>
  </body>
</html>

src/templates/messages_display.html
{% if messages %}
  <div class="messages">
    <ul class="messages">
      {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {%if "html_safe" in message.tags %}
          {{ message|safe }}
        {% else %}
          {{ message }}
        {%endif%}
        </li>
      {% endfor %}
    </ul>
  </div>
{% endif %}

src/templates/post_detail.html
{%extends "base.html" %}
{% load urlfy %}

{% block head_title %}
{{instance.title}} | {{block.super}}
{% endblock head_title %}
{% block content %}
<div class="col-sm-6 col-sm-offset-3">
  <!-- Note the instance.image.url the url extra and it's class  -->
  {% if instance.image %}
  <img src="{{instance.image.url}}" alt="Image" class="img-responsive">
  {% endif %}
  <h1>{{title}}<small>{% if instance.draft %} <span style='color:red;'>Draft </span>{% endif %}{{instance.publish}}</small></h1>
  {% if instance.user.get_full_name %}
  <p>Author: {{instance.user.get_full_name}}</p>
  {% endif %}
  <p>
  <div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="button_count" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
  <hr>
  </p>
  <!-- <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
Facebook
</a>
<a href="https://twitter.com/home?status={{instance.content|urlify}}%20{{request.build_absolute_uri}}">
Twitter
</a>
<a href='https://plus.google.com/share?url={{request.build_absolute_uri}}'>Share on Google+</a>

<a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}/&title={{instance.title}}&summary={{share_string}}&source={{request.build_absolute_uri}}">
Linkedin
</a> -->
<!--
<a href="http://www.reddit.com/submit?url={{request.build_absolute_uri}}/&title={{share_string}}.">Share on Reddit</a>-->
<div class="row">
  <div class="col-sm-12">
<div class="post-detail-item">{{instance.get_markdown}}</div><br>
<!-- This div is newly added -->
<div>
  {{ instance.comment_set.all}}
</div>
  <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>
</div>
</div>
</div>
{%endblock content%}

src/templates/post_form.html
{%extends "base.html" %}
{% load crispy_forms_tags %}
{% block head_extra %}
{{form.media}}
{% endblock head_extra %}
{% block content%}
    <div class="col-sm-6">
      <h1>Preview</h1>
      <hr>
      <div class="content-preview">
        <h3 id = "preview-title"></h3>
        <!-- The content is added here -->
        <p id = "preview-content"></p>
      </div>
    </div>
    <div class="col-sm-6 ">
    <form action="" method="POST" enctype="multipart/form-data">
    <h1>Form</h1>
    <hr>
    {% csrf_token %}
    <!-- {{form.as_p}} is changed to -->
    {{form | crispy}}
    <input type="submit" class='btn btn-default' value="Create Post">
    </form>
    </div>
{% endblock content %}

src/templates/post_list.html
{% extends "base.html" %}
{% block content %}
  <div class="col-sm-6 col-sm-offset-3">
    <h1>{{title}}</h1>
    <!-- We add in row here to have space after the search and input box -->
  <form method="GET" class = "row">
    <div class="col-sm-6">
      <div class="input-group">
        <input class = "form-control" type="text" name="q" value="{{request.GET.q}}" placeholder="Search posts">
        <!-- We made a span with this class to make sure that that full space is utilized for text. -->
        <span class = "input-group-btn">
        <!-- <input class = "btn btn-default" type="submit" value="Search"><br> -->
        <button class="btn btn-default" type="submit"><i class="fas fa-search"></i></button>
        </span>
      </div>
    </div>
  </form>
  {% for obj in object_list %}
  <div class="row">
  <div class="col-sm-12">
    <div class="thumbnail">
      {% if obj.image %}
      <img src="{{obj.image.url}}" alt="Image" class="img-responsive">
      {% endif %}
      <!-- Here post-detail-item is added as the class -->
      <div class="caption post-detail-item">
        {% if obj.draft %}<h3>Staff only: Draft</h3>{% endif %} {% if obj.publish > today %}<h3>Staff only: Future Post</h3> {% endif %}
        <h3><a href="{{obj.get_absolute_url}}">{{obj.title}}</a><small>{{obj.publish}}</small></h3>
        <p>{% if obj.user.get_full_name%}Author: {{obj.user.get_full_name}}{%endif%}</p>
        <!-- Here we removed the paragraph tag for design issues -->
        {{obj.get_markdown | truncatechars_html:9 }}
        <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">View</a> </p>
      </div>
    </div>
  </div>
  <hr/>
  </div>
  {% endfor %}

  <div class="pagination">
    <span class="step-links">
        {% if object_list.has_previous %}
        <!-- The end of href is changed -->
            <a href="?{{page_request_var}}={{ object_list.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
        </span>

        {% if object_list.has_next %}
            <a href="?{{page_request_var}}={{ object_list.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">next</a>
        {% endif %}
    </span>
</div>

  </div>
{% endblock content %}